################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
INO_SRCS += \
..\DiveIno.ino 

CPP_SRCS += \
..\Buhlmann.cpp \
..\LastDive.cpp \
..\Logbook.cpp \
..\Settings.cpp \
..\View.cpp \
..\sloeber.ino.cpp 

C_SRCS += \
..\Grotesk16x32.c \
..\SevenSegNumFontPlusPlus.c \
..\SevenSeg_XXXL.c \
..\TinyFont.c 

C_DEPS += \
.\Grotesk16x32.c.d \
.\SevenSegNumFontPlusPlus.c.d \
.\SevenSeg_XXXL.c.d \
.\TinyFont.c.d 

LINK_OBJ += \
.\Buhlmann.cpp.o \
.\Grotesk16x32.c.o \
.\LastDive.cpp.o \
.\Logbook.cpp.o \
.\Settings.cpp.o \
.\SevenSegNumFontPlusPlus.c.o \
.\SevenSeg_XXXL.c.o \
.\TinyFont.c.o \
.\View.cpp.o \
.\sloeber.ino.cpp.o 

INO_DEPS += \
.\DiveIno.ino.d 

CPP_DEPS += \
.\Buhlmann.cpp.d \
.\LastDive.cpp.d \
.\Logbook.cpp.d \
.\Settings.cpp.d \
.\View.cpp.d \
.\sloeber.ino.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
Buhlmann.cpp.o: ..\Buhlmann.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

DiveIno.o: ..\DiveIno.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

Grotesk16x32.c.o: ..\Grotesk16x32.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -flto -fno-fat-lto-objects -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

LastDive.cpp.o: ..\LastDive.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

Logbook.cpp.o: ..\Logbook.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

Settings.cpp.o: ..\Settings.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

SevenSegNumFontPlusPlus.c.o: ..\SevenSegNumFontPlusPlus.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -flto -fno-fat-lto-objects -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

SevenSeg_XXXL.c.o: ..\SevenSeg_XXXL.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -flto -fno-fat-lto-objects -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

TinyFont.c.o: ..\TinyFont.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -flto -fno-fat-lto-objects -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

View.cpp.o: ..\View.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

sloeber.ino.cpp.o: ..\sloeber.ino.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Users\Kornel_Schrenk\Tools\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\cores\arduino" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\mega" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\DS1307RTC" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\SdFat\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MS5803_14" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Time" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Adafruit_BluefruitLE_nRF51\utility" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\Arduino-IRremote-Due" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\MAX17043" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\TimerFreeTone" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SoftwareSerial\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\SPI\src" -I"C:\Users\Kornel_Schrenk\Tools\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\libraries\Wire\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\ArduinoJson\src" -I"C:\Users\Kornel_Schrenk\Documents\Arduino\libraries\UTFT_SdRaw\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '


