package hu.diveino.droid.service;

public enum SerialApiMessageType {
    GENERAL_VERSION, GENERAL_RESET, GENERAL_CLEAR_SURFACE,
    LOGBOOK_INFO, LOGBOOK_PROFILE_INFO,
    SETTINGS_INFO, SETTINGS_AUTO, SETTINGS_DEFAULT, SETTINGS_SOUND, SETTINGS_METRIC, SETTINGS_PRESSURE, SETTINGS_OXYGEN, SETTINGS_DATETIME,
    DIAG_TEMP, DIAG_PRES, DIAG_BAT, DIAG_DATE, DIAG_TIMESTAMP
}
